crud/urls.py
from django.urls import path
from . import views


app_name = 'crud'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login?next=<str:next>', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('references', views.references, name='references'),
    path('users', views.users, name="users"),
    path('update?id=<int:pk>', views.update_user, name="update"),
    path('delete?id=<int:pk>', views.delete_user, name='delete'),
]

usermgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('crud.urls', namespace='crud'))
)

crud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


# Create your models here.

class Detail(models.Model):
    MARITAL_STATUS = (
        (_('Yes'), _('Married')),
        (_('No'), _('Not Married')),
    )
    # personal information
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(help_text=_("Phone number"), max_length=20, null=False)
    dob = models.DateField(help_text=_("Date of birth"), null=False)
    married = models.CharField(max_length=25, choices=MARITAL_STATUS, help_text=_("Marital status"), null=False)
    kids = models.PositiveIntegerField(default=0, help_text=_("Number of kids"), null=False)
    # work information
    doh = models.DateField(default=timezone.now, help_text=_("Date of hiring"), null=False)
    title = models.CharField(help_text=_("Job title"), max_length=255, null=False)
    duration = models.PositiveIntegerField(help_text=_("Contract duration"), null=False)
    # other information
    updated = models.DateTimeField(auto_now=True, help_text=_("Datetime model was last modified"))

    def age(self):
        year = timezone.datetime.date(timezone.datetime.now()).year
        dob_year = self.dob.year
        return year - dob_year
    
    def eoh(self):
        doh = timezone.datetime(
            self.doh.year,
            self.doh.month,
            self.doh.day
        )
        return timezone.datetime.date(doh + timezone.timedelta(days=self.duration*365))

    class Meta:
        ordering = ("-doh", "-duration")
        verbose_name = "Detail"
        verbose_name_plural = "Details"
    

crud/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from .models import Detail
import re


class UserForm(forms.ModelForm):
    confirm_password = forms.CharField(
        max_length=255, 
        label=_("Confirm password"),
        help_text=_("Password should be 9 characters minimum, contain at least one lowercase, uppercase, symbol and number. No whitespace allowed e.g., A1!.#laN87@Jp"), 
        widget=forms.PasswordInput
    )
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password")
        labels = {
            "first_name": _("First name"),
            "last_name": _("Last name"), 
            "email": _("Email"),
            "username": _("Username"),
            "password": _("Password"),
        }
        widgets = {
            "password": forms.PasswordInput,
        }
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error(
                "password", 
                ValidationError(
                    message=_("Passwords do not match"),
                    code="mismatch"
                )
            )
            self.add_error(
                "confirm_password", 
                ValidationError(
                    message=_("Passwords do not match"),
                    code="mismatch"
                )
            )
            raise ValidationError(
                message=_("Passwords do not match"),
                code="mismatch"
            )


class DetailForm(forms.ModelForm):
    class Meta:
        model = Detail
        fields = ["phone", "dob", "married", "kids", "title", "duration"]
        labels = {
            "phone": _("Phone number"),
            "dob": _("Date of birth"),
            "married": _("Married"),
            "kids": _("Number of kids"),
            "title": _("Job title"),
            "duration": _("Contract Duration"),
        }
        widgets = {
            "phone": forms.TextInput(attrs={
                "placeholder": "237xxxxxxxxx"
            }),
            "dob": forms.DateInput(attrs={
                "placeholder": "YYYY-MM-DD",
            }),
            "title": forms.TextInput(attrs={
                "placeholder": _("Network/Security Engineer")
            }),
            "duration": forms.TextInput(attrs={
                "placeholder": "3"
            })
        }


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        label=_("Username"),
        help_text=_("A unique username"),
        required=True
    )
    password = forms.CharField(
        max_length=255,
        required=True,
        label=_("Password"),
        help_text=_("Minimum length is 9, at least one symbol, lower and upper case letters, number"),
        widget=forms.PasswordInput
    )

    def clean(self):
        cp = self.cleaned_data["password"]
        
        if len(cp) < 9:
            self.add_error(
                field="password",
                error=ValidationError(
                    message=_("Minimum password length is 9!"),
                    code="short"
                )
            )

crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import UserForm, DetailForm, LoginForm
from .models import Detail

# Create your views here.

def home(request):
    return render(
        request=request, 
        template_name='main/home.html',
        context={}
    )


def register(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        detail_form = DetailForm(data=request.POST)
        if user_form.is_valid() and detail_form.is_valid():
            new_user: User = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["confirm_password"])
            new_user.save()
            new_user_detail: Detail = detail_form.save(commit=False)
            new_user_detail.user = new_user
            new_user_detail.save()
            return redirect("crud:login", "home")
    else:
        user_form = UserForm()
        detail_form = DetailForm()
    
    return render(
        request=request,
        template_name="main/register.html",
        context={
            "uform": user_form,
            "dform": detail_form,
        }
    )


def login_view(request, next):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd["username"]
            password = cd["password"]
            user = authenticate(
                reuqest=request,
                username=username,
                password=password
            )
            if user is not None:
                login(request=request, user=user)
                return redirect(f"crud:{next}")
    else:
        form = LoginForm()
    
    return render(
        request=request,
        template_name="main/login.html",
        context={
            "form": form
        }
    )


def logout_view(request):
    if request.user.is_authenticated:
        logout(request=request)
    return redirect("crud:home")


def references(request):
    return render(
        request=request,
        template_name="main/references.html",
        context={}
    )


def users(request):
    object_list = User.objects.all().exclude(username="admin")
    paginator = Paginator(object_list=object_list, per_page=5)
    page_num = request.GET.get("page")
    try:
        users = paginator.page(page_num)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    
    return render(
        request=request,
        template_name="main/users.html",
        context={
            "users": users,
        }
    )


def update_user(request, pk):
    user: User = get_object_or_404(User, id=pk)
    detail: Detail = get_object_or_404(Detail, user=user)
    if request.method == "POST":
        user_form = UserForm(instance=user, data=request.POST)
        detail_form = DetailForm(instance=detail, data=request.POST)
        if user_form.is_valid() and detail_form.is_valid():
            user_form.save()
            detail_form.save()
            return redirect("crud:users")
    else:
        user_form = UserForm(instance=user)
        detail_form = DetailForm(instance=detail)
    
    return render(
        request=request,
        template_name="main/update.html",
        context={
            "uform": user_form,
            "dform": detail_form,
        }
    )


def delete_user(request, pk):
    user = get_object_or_404(User, id=pk)
    user.delete()
    return redirect("crud:users")

crud/templates/main/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% block header_link %}

{% endblock %}

{% block header_script %}

{% endblock %}

{% block title %}{% translate "Dashboard" %}{% endblock %}

{% block main %}

{% endblock %}

crud/templates/main/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header_link %}
<link href="{% static 'css/home.css' %}" rel="stylesheet">
{% endblock %}

{% block header_script %}
<script src="{% static 'js/home.js' %}" type="module" defer></script>
{% endblock %}

{% block title %}{% translate "Home" %}{% endblock %}

{% block main %}

<section class="home-section">
    <article class="home-article-1">
        <h1>{% translate "It&apos;s simple and enjoyable!" %}</h1>
        <p>{% translate "Managing users has never been so simple and enjoyable at the same time. No need to be overwhelmed anymore, we have your back." %}</p>
        <div class="home-links">
            <a href="{% url 'crud:login' 'home' %}">{% translate "Login now" %}</a>
            <a href="{% url 'crud:register' %}">{% translate "Register now" %}</a>
        </div>
    </article>
    <article class="home-article-2">
        <img src="{% static 'img/home_img.svg' %}">
    </article>
</section>

{% endblock %}

crud/templates/main/login.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header_link %}
<link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block header_script %}
<script src="{% static 'js/login.js' %}" type="module" defer></script>
{% endblock %}

{% block title %}{% translate "Login" %}{% endblock %}

{% block main %}

{% translate "Login" as login %}

<section class="two-pane">
    <article class="two-pane-form">
        <h2>{% translate "Login Form" %}</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-container">
                <div class="user-form">
                    {% for field in form %}
                        <div class="field-wrapper">
                            <p>{{ field.label_tag }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="error">*{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <input type="submit" value="{{ login }}">
        </form>
    </article>
    <article class="section-image">
        <img src="{% static 'img/login_img.svg' %}">
    </article>
</section>

{% endblock %}

crud/templates/main/pagination.html
<div class="pagination-container">
    <a {% if page.number != 1 %}href="?page=1" {% else %}class="no-previous"{% endif %}>
        1
    </a>
    <a {% if page.has_previous %} href="?page={{ page.previous_page_number }}" class="previous"{% else %}class="no-previous"{% endif %}>
        &lt;
    </a>
    <span>{{ page.number }}</span>
    <a {% if page.has_next %} href="?page={{ page.next_page_number }}" class="next"{% else %}class="no-next"{% endif %}>
        &gt;
    </a>
    <a {% if page.number != page.paginator.num_pages %}href="?page={{ page.paginator.num_pages }}" {% else %}class="no-next"{% endif %}>
        {{ page.paginator.num_pages }}
    </a>
</div>

crud/templates/main/references.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header_link %}
<link href="{% static 'css/references.css' %}" rel="stylesheet">
{% endblock %}

{% block header_script %}{% endblock %}

{% block title %}{% translate "References" %}{% endblock %}

{% block main %}

<section class="section-references">
    <h1>{% translate "Tribute to resource authors" %}</h1>
    <table>
        <thead>
            <tr>
                <th>{% translate "Resource" %}</th>
                <th>{% translate "Type" %}</th>
                <th>{% translate "Location" %}</th>
                <th>{% translate "Author(s)" %}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{% translate "Dropdown arrow" %}</td>
                <td>{% translate "Icon" %}</td>
                <td>{% translate "Navigation bar" %}</td>
                <td>Google (<a href="https://fonts.google.com/icons" target="_blank">Google icons</a>)</td>
            </tr>
            <tr>
                <td>{% translate "Great Britain and France flags" %}</td>
                <td>{% translate "Image" %}</td>
                <td>{% translate "Navigation bar" %}</td>
                <td>Wikipedia (<a href="https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population" target="_blank">Wikipedia country list</a>)</td>
            </tr>
            <tr>
                <td>{% translate "Girl with books and pen in hand" %}</td>
                <td>{% translate "Illustration" %}</td>
                <td>{% translate "Home page" %}</td>
                <td>Lunacy (<a href="https://icons8.com" target="_blank">icons8.com</a>)</td>
            </tr>
            <tr>
                <td>{% translate "Work space and graph with web browser in background" %}</td>
                <td>{% translate "Illustration" %}</td>
                <td>{% translate "Home page" %}</td>
                <td>Lunacy (<a href="https://icons8.com" target="_blank">icons8.com</a>)</td>
            </tr>
            <tr>
                <td>{% translate "Young woman with stack of books" %}</td>
                <td>{% translate "Illustration" %}</td>
                <td>{% translate "Login page" %}</td>
                <td>Lunacy (<a href="https://icons8.com" target="_blank">icons8.com</a>)</td>
            </tr>
            <tr>
                <td>{% translate "Young boys and young girl jumping" %}</td>
                <td>{% translate "Illustration" %}</td>
                <td>{% translate "Registration page" %}</td>
                <td>Lunacy (<a href="https://icons8.com" target="_blank">icons8.com</a>)</td>
            </tr>
            <tr>
                <td>{% translate "Students making ok sign" %}</td>
                <td>{% translate "Illustration" %}</td>
                <td>{% translate "Update page" %}</td>
                <td>Lunacy (<a href="https://icons8.com" target="_blank">icons8.com</a>)</td>
            </tr>
        </tbody>
    </table>
    <p>{% translate "Authors, once more, thank you for your awesome resources." %}</p>
</section>

{% endblock %}

crud/templates/main/register.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header_link %}
<link href="{% static 'css/register.css' %}" rel="stylesheet">
{% endblock %}

{% block header_script %}
<script src="{% static 'js/register.js' %}" type="module" defer></script>
{% endblock %}

{% block title %}{% translate "Registration" %}{% endblock %}

{% block main %}

{% translate "Register" as signup %}

<section class="two-pane">
    <article class="section-image">
        <img src="{% static 'img/register_img.svg' %}">
    </article>
    <article class="two-pane-form">
        <h2>{% translate "Registration Form" %}</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-container">
                <div class="user-form">
                    {% for field in uform %}
                        <div class="field-wrapper">
                            <p>{{ field.label_tag }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="error">*{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
                <div class="detail-form">
                    {% for field in dform %}
                        <div class="field-wrapper">
                            <p>{{ field.label_tag }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="error">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <input type="submit" value="{{ signup }}">
        </form>
    </article>
</section>

{% endblock %}

crud/templates/main/update.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header_link %}
<link href="{% static 'css/register.css' %}" rel="stylesheet">
<link href="{% static 'css/update.css' %}" rel="stylesheet">
{% endblock %}

{% block header_script %}
<script src="{% static 'js/register.js' %}" type="module" defer></script>
{% endblock %}

{% block title %}{% translate "Update" %}{% endblock %}

{% block main %}

{% translate "Update" as update %}

<section class="two-pane">
    <article class="section-image">
        <img src="{% static 'img/update_img.svg' %}">
    </article>
    <article class="two-pane-form">
        <h2>{% translate "Update User" %}</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-container">
                <div class="user-form">
                    {% for field in uform %}
                        <div class="field-wrapper">
                            <p>{{ field.label_tag }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="error">*{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
                <div class="detail-form">
                    {% for field in dform %}
                        <div class="field-wrapper">
                            <p>{{ field.label_tag }}</p>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="error">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <input type="submit" value="{{ update }}">
        </form>
    </article>
</section>

{% endblock %}

crud/templates/main/users.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block header_link %}
<link href="{% static 'css/references.css' %}" rel="stylesheet">
<link href="{% static 'css/users.css' %}" rel="stylesheet"/>
{% endblock %}

{% block header_script %}
<script href="{% static 'js/users.js' %}" type="module" defer></script>
{% endblock %}

{% block title %}{% translate "Users" %}{% endblock %}

{% block main %}

<section class="section-references">
    <h1>{% translate "Users list" %}</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>{% translate "First name" %}</th>
                <th>{% translate "Last name" %}</th>
                <th>{% translate "Birth date" %}</th>
                <th>{% translate "Married" %}</th>
                <th>{% translate "Kids" %}</th>
                <th>{% translate "Hire Date" %}</th>
                <th>{% translate "Job title" %}</th>
                <th>{% translate "Contract duration" %}</th>
                <th>{% translate "Phone" %}</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.detail.dob }}</td>
                    <td>{{ user.detail.married }}</td>
                    <td>{{ user.detail.kids }}</td>
                    <td>{{ user.detail.doh }}</td>
                    <td>{{ user.detail.title }}</td>
                    <td>{{ user.detail.duration }}</td>
                    <td>+{{ user.detail.phone }}</td>
                    <td><a href="{% url 'crud:update' user.id %}" class="update">{% translate "Update" %}</a></td>
                    <td><a href="{% url 'crud:delete' user.id %}" class="delete">{% translate "Delete" %}</a></td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
    {% include "main/pagination.html" with page=users %}
    <p>{% translate "Administrators, please make sure to notify users before modifications." %}</p>
</section>

{% endblock %}