crud/urls.py
from django.urls import path
from . import views


app_name = 'crud'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login?next=<str:next>', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('references', views.references, name='references'),
    path('users', views.users, name="users"),
    path('update?id=<int:pk>', views.update_user, name="update"),
    path('delete?id=<int:pk>', views.delete_user, name='delete'),
]

usermgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('crud.urls', namespace='crud'))
)

crud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


# Create your models here.

class Detail(models.Model):
    MARITAL_STATUS = (
        (_('Yes'), _('Married')),
        (_('No'), _('Not Married')),
    )
    # personal information
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(help_text=_("Phone number"), max_length=20, null=False)
    dob = models.DateField(help_text=_("Date of birth"), null=False)
    married = models.CharField(max_length=25, choices=MARITAL_STATUS, help_text=_("Marital status"), null=False)
    kids = models.PositiveIntegerField(default=0, help_text=_("Number of kids"), null=False)
    # work information
    doh = models.DateField(default=timezone.now, help_text=_("Date of hiring"), null=False)
    title = models.CharField(help_text=_("Job title"), max_length=255, null=False)
    duration = models.PositiveIntegerField(help_text=_("Contract duration"), null=False)
    # other information
    updated = models.DateTimeField(auto_now=True, help_text=_("Datetime model was last modified"))

    def age(self):
        year = timezone.datetime.date(timezone.datetime.now()).year
        dob_year = self.dob.year
        return year - dob_year
    
    def eoh(self):
        doh = timezone.datetime(
            self.doh.year,
            self.doh.month,
            self.doh.day
        )
        return timezone.datetime.date(doh + timezone.timedelta(days=self.duration*365))

    class Meta:
        ordering = ("-doh", "-duration")
        verbose_name = "Detail"
        verbose_name_plural = "Details"
    

crud/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from .models import Detail
import re


class UserForm(forms.ModelForm):
    confirm_password = forms.CharField(
        max_length=255, 
        label=_("Confirm password"),
        help_text=_("Password should be 9 characters minimum, contain at least one lowercase, uppercase, symbol and number. No whitespace allowed e.g., A1!.#laN87@Jp"), 
        widget=forms.PasswordInput
    )
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password")
        labels = {
            "first_name": _("First name"),
            "last_name": _("Last name"), 
            "email": _("Email"),
            "username": _("Username"),
            "password": _("Password"),
        }
        widgets = {
            "password": forms.PasswordInput,
        }
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error(
                "password", 
                ValidationError(
                    message=_("Passwords do not match"),
                    code="mismatch"
                )
            )
            self.add_error(
                "confirm_password", 
                ValidationError(
                    message=_("Passwords do not match"),
                    code="mismatch"
                )
            )
            raise ValidationError(
                message=_("Passwords do not match"),
                code="mismatch"
            )


class DetailForm(forms.ModelForm):
    class Meta:
        model = Detail
        fields = ["phone", "dob", "married", "kids", "title", "duration"]
        labels = {
            "phone": _("Phone number"),
            "dob": _("Date of birth"),
            "married": _("Married"),
            "kids": _("Number of kids"),
            "title": _("Job title"),
            "duration": _("Contract Duration"),
        }
        widgets = {
            "phone": forms.TextInput(attrs={
                "placeholder": "237xxxxxxxxx"
            }),
            "dob": forms.DateInput(attrs={
                "placeholder": "YYYY-MM-DD",
            }),
            "title": forms.TextInput(attrs={
                "placeholder": _("Network/Security Engineer")
            }),
            "duration": forms.TextInput(attrs={
                "placeholder": "3"
            })
        }


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        label=_("Username"),
        help_text=_("A unique username"),
        required=True
    )
    password = forms.CharField(
        max_length=255,
        required=True,
        label=_("Password"),
        help_text=_("Minimum length is 9, at least one symbol, lower and upper case letters, number"),
        widget=forms.PasswordInput
    )

    def clean(self):
        cp = self.cleaned_data["password"]
        
        if len(cp) < 9:
            self.add_error(
                field="password",
                error=ValidationError(
                    message=_("Minimum password length is 9!"),
                    code="short"
                )
            )

crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import UserForm, DetailForm, LoginForm
from .models import Detail

# Create your views here.

def home(request):
    return render(
        request=request, 
        template_name='main/home.html',
        context={}
    )


def register(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        detail_form = DetailForm(data=request.POST)
        if user_form.is_valid() and detail_form.is_valid():
            new_user: User = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["confirm_password"])
            new_user.save()
            new_user_detail: Detail = detail_form.save(commit=False)
            new_user_detail.user = new_user
            new_user_detail.save()
            return redirect("crud:login", "home")
    else:
        user_form = UserForm()
        detail_form = DetailForm()
    
    return render(
        request=request,
        template_name="main/register.html",
        context={
            "uform": user_form,
            "dform": detail_form,
        }
    )


def login_view(request, next):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd["username"]
            password = cd["password"]
            user = authenticate(
                reuqest=request,
                username=username,
                password=password
            )
            if user is not None:
                login(request=request, user=user)
                return redirect(f"crud:{next}")
    else:
        form = LoginForm()
    
    return render(
        request=request,
        template_name="main/login.html",
        context={
            "form": form
        }
    )


def logout_view(request):
    if request.user.is_authenticated:
        logout(request=request)
    return redirect("crud:home")


def references(request):
    return render(
        request=request,
        template_name="main/references.html",
        context={}
    )


def users(request):
    object_list = User.objects.all().exclude(username="admin")
    paginator = Paginator(object_list=object_list, per_page=5)
    page_num = request.GET.get("page")
    try:
        users = paginator.page(page_num)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    
    return render(
        request=request,
        template_name="main/users.html",
        context={
            "users": users,
        }
    )


def update_user(request, pk):
    user: User = get_object_or_404(User, id=pk)
    detail: Detail = get_object_or_404(Detail, user=user)
    if request.method == "POST":
        user_form = UserForm(instance=user, data=request.POST)
        detail_form = DetailForm(instance=detail, data=request.POST)
        if user_form.is_valid() and detail_form.is_valid():
            user_form.save()
            detail_form.save()
            return redirect("crud:users")
    else:
        user_form = UserForm(instance=user)
        detail_form = DetailForm(instance=detail)
    
    return render(
        request=request,
        template_name="main/update.html",
        context={
            "uform": user_form,
            "dform": detail_form,
        }
    )


def delete_user(request, pk):
    user = get_object_or_404(User, id=pk)
    user.delete()
    return redirect("crud:users")

crud/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="author" content="Chuye Brian">
        <meta name="description" content="Simple web application for managing site users.">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">

        <!-- Links -->
        <link href="{% static 'img/icons/logo.ico' %}" rel="icon">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
        {% block header_link %}
        {% endblock %}

        <!-- Scripts -->
        <script src="{% static 'js/base.js' %}" type="module" defer></script>
        {% block header_script %}
        {% endblock %}

        <title>{% block title %}{% endblock %} | usermgmt</title>
    </head>
    <body>
        <header>
            <nav>
                <div class="nav-1">
                    <a href="{% url 'crud:home' %}">
                        <img src="{% static 'img/icons/nav_logo.ico' %}">
                    </a>
                </div>
                <div class="nav-2">
                    <span class="material-symbols-outlined desktop-hide">menu</span>
                    <ul class="mobile-hide">
                        <li><a href="{% url 'crud:register' %}" id="register-a" class="register-a">{% translate "Add User" %}</a></li>
                        <li><a href="{% url 'crud:users' %}" id="users-a">{% translate "Users" %}</a></li>
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'crud:login' 'home' %}" id="login-a">{% translate "Login" %}</a></li>
                        {% endif %}
                        <li><a href="{% url 'crud:references' %}" id="references-a">{% translate "References" %}</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'crud:logout' %}" id="logout-a">{% translate "Logout" %}</a></li>
                        {% endif %}
                        <li class="language-dropdown">
                            <p class="current-language">
                                <span>{% get_current_language as LANGUAGE_CODE %}{{ LANGUAGE_CODE }}</span> 
                                <span class="material-symbols-outlined">arrow_drop_down</span>
                            </p>
                            <div class="desktop-hide supported-languages">
                                <div class="languages">
                                    <p><img src="{% static 'img/flags/uk_flag.svg' %}"> <span>en</span></p>
                                    <p><img src="{% static 'img/flags/france_flag.svg' %}"> <span>fr</span></p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <main>
            {% block main %}
            {% endblock %}
        </main>
        <footer>
            <p>&copy;2024 {% translate "Site powered by " %}<a href="https://prantix.com" target="_blank">prantix.com</a></p>
        </footer>
    </body>
</html>